version: '3.7'
services:

  utils-api:
    build: ./python
    container_name: texas-real-foods-utils-api
    networks:
    - core
    - texas-real-foods

  api:
    build:
      context: ./go
      dockerfile: cmd/api/Dockerfile
    container_name: texas-real-foods-api
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/api/.env

  authenticator:
    build:
      context: ./go
      dockerfile: cmd/authenticator/Dockerfile
    container_name: texas-real-foods-authenticator
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/authenticator/.env

  router:
    build:
      context: ./go
      dockerfile: cmd/router/Dockerfile
    container_name: texas-real-foods-router
    networks:
    - core
    - postgres
    - texas-real-foods

  web-updater:
    build:
      context: ./go
      dockerfile: cmd/auto-updater/scraper/Dockerfile
    container_name: texas-real-foods-updater-web
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/auto-updater/scraper/.env

  yelp-updater:
    build:
      context: ./go
      dockerfile: cmd/auto-updater/yelp/Dockerfile
    container_name: texas-real-foods-updater-yelp
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/auto-updater/yelp/.env

  google-updater:
    build:
      context: ./go
      dockerfile: cmd/auto-updater/google/Dockerfile
    container_name: texas-real-foods-updater-google
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/auto-updater/google/.env

  syncer:
    build:
      context: ./go
      dockerfile: cmd/syncer/Dockerfile
    container_name: texas-real-foods-syncer
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/syncer/.env

  mail-relay:
    build:
      context: ./go
      dockerfile: cmd/mail-relay/Dockerfile
    container_name: texas-real-foods-mail-relay
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/mail-relay/.env

  api-documentation:
    build:
      context: ./docs/openapi
    container_name: trf-api-documentation
    networks:
    - core
    - texas-real-foods
    environment:
      BASE_URL: /api/docs

networks:
  core:
    name: core
  postgres:
    name: postgres
  texas-real-foods:
    name: texas-real-foods