version: '3.7'
services:

  utils-api:
    build: ./python
    restart: unless-stopped
    container_name: texas-real-foods-utils-api
    networks:
    - core
    - texas-real-foods

  api:
    build:
      context: ./go
      dockerfile: cmd/api/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-api
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/api/.env

  load-balancer:
    build:
      context: ./go
      dockerfile: cmd/load-balancer/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-api-load-balancer
    networks:
    - core
    - texas-real-foods

  api-backend-replica-1:
    build:
      context: ./go
      dockerfile: cmd/api/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-api-1
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/api/.env

  api-backend-replica-2:
    build:
      context: ./go
      dockerfile: cmd/api/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-api-2
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/api/.env

  api-backend-replica-3:
    build:
      context: ./go
      dockerfile: cmd/api/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-api-3
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/api/.env

  authenticator:
    build:
      context: ./go
      dockerfile: cmd/authenticator/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-authenticator
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/authenticator/.env

  router:
    build:
      context: ./go
      dockerfile: cmd/router/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-router
    networks:
    - core
    - postgres
    - texas-real-foods

  web-updater:
    build:
      context: ./go
      dockerfile: cmd/auto-updater/scraper/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-updater-web
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/auto-updater/scraper/.env

  yelp-updater:
    build:
      context: ./go
      dockerfile: cmd/auto-updater/yelp/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-updater-yelp
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/auto-updater/yelp/.env

  # google-updater:
  #   build:
  #     context: ./go
  #     dockerfile: cmd/auto-updater/google/Dockerfile
  #   container_name: texas-real-foods-updater-google
  #   networks:
  #   - core
  #   - postgres
  #   - texas-real-foods
  #   env_file:
  #   - go/cmd/auto-updater/google/.env

  syncer:
    build:
      context: ./go
      dockerfile: cmd/syncer/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-syncer
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/syncer/.env

  analyser:
    build:
      context: ./go
      dockerfile: cmd/timeseries-analyser/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-analyser
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/timeseries-analyser/.env


  mail-relay:
    build:
      context: ./go
      dockerfile: cmd/mail-relay/Dockerfile
    restart: unless-stopped
    container_name: texas-real-foods-mail-relay
    networks:
    - core
    - postgres
    - texas-real-foods
    env_file:
    - go/cmd/mail-relay/.env

  api-documentation:
    build:
      context: ./docs/openapi
    restart: unless-stopped
    container_name: trf-api-documentation
    networks:
    - core
    - texas-real-foods
    environment:
      BASE_URL: /api/docs

  hermes-server:
    build:
      context: ./go/cmd/hermes
    restart: unless-stopped
    container_name: texas-real-foods-hermes
    expose:
    - 7789/udp
    - 8080
    networks:
    - texas-real-foods
    - core
    environment:
      LOG_LEVEL: DEBUG

networks:
  core:
    name: core
  postgres:
    name: postgres
  texas-real-foods:
    name: texas-real-foods